[package]
name = "chemish"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
ash = "0.38.0+1.3.281"
ash-window = "0.13.0"
nalgebra = "0.33.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
winit = "0.30.9"
